version: '3'
services:
    server:
        build: ./server
        ports:
            - "8080:8080"
            - "61616:61616"
    agentude:
        build: ./agents/AgentUDE17
    adapter:
        build: ./adapter
