kind: Service
apiVersion: v1
metadata:
  name: nfs-server-service
spec:
  clusterIP: 10.96.10.10
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
