apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unique-storage-claim
  labels:
    demo: nfs-pv-provisioning
  annotations:
    storage-class: any
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
